version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: go_mint_postgres
    environment:
      POSTGRES_DB: go_mint_db
      POSTGRES_USER: go_mint_user
      POSTGRES_PASSWORD: go_mint_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 