export enum NotificationType {
    // Friend related notifications
    FRIEND_REQUEST_RECEIVED = 'FRIEND_REQUEST_RECEIVED',
    FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
    FRIEND_REQUEST_REJECTED = 'FRIEND_REQUEST_REJECTED',
    FRIEND_REMOVED = 'FRIEND_REMOVED',
    FRIEND_BLOCKED = 'FRIEND_BLOCKED',
    FRIEND_UNBLOCKED = 'FRIEND_UNBLOCKED',

    // Chat related notifications
    NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE',
    CHAT_MESSAGE_READ = 'CHAT_MESSAGE_READ',
    CHAT_TYPING = 'CHAT_TYPING',

    // Community chat related notifications
    NEW_COMMUNITY_MESSAGE = 'NEW_COMMUNITY_MESSAGE',
    COMMUNITY_TYPING = 'COMMUNITY_TYPING',
    COMMUNITY_CHAT_CREATED = 'COMMUNITY_CHAT_CREATED',
    COMMUNITY_CHAT_DEACTIVATED = 'COMMUNITY_CHAT_DEACTIVATED',

    // Token related notifications
    TOKEN_CREATED = 'TOKEN_CREATED',
    TOKEN_UPDATED = 'TOKEN_UPDATED',
    TOKEN_DELETED = 'TOKEN_DELETED',
    TOKEN_RESTORED = 'TOKEN_RESTORED',
    TOKEN_TRANSFERRED = 'TOKEN_TRANSFERRED',
    TOKEN_MINTED = 'TOKEN_MINTED',
    TOKEN_BURNED = 'TOKEN_BURNED',
    TOKEN_PAUSED = 'TOKEN_PAUSED',
    TOKEN_RESUMED = 'TOKEN_RESUMED',
    TOKEN_FROZEN = 'TOKEN_FROZEN',
    TOKEN_UNFROZEN = 'TOKEN_UNFROZEN',
    TOKEN_MINT_SUCCESS = 'TOKEN_MINT_SUCCESS',
    TOKEN_MINT_FAILED = 'TOKEN_MINT_FAILED',
    TOKEN_BURN_SUCCESS = 'TOKEN_BURN_SUCCESS',
    TOKEN_BURN_FAILED = 'TOKEN_BURN_FAILED',
    TOKEN_TRANSFER_SUCCESS = 'TOKEN_TRANSFER_SUCCESS',
    TOKEN_TRANSFER_FAILED = 'TOKEN_TRANSFER_FAILED',

    TOKEN_PURCHASED = 'TOKEN_PURCHASED',
    TOKEN_SOLD = 'TOKEN_SOLD',

} 